### ISSUE TITLE
"sudo yum downgrade scylla"  command failed in rolling-upgrade in CI jobs

### ISSUE THREAD

**Issue by temichus** [scylladb/scylla-cqlsh#23]
Jenkins jobs: 
[rolling-upgrade-centos8-test](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos8-test/185/) build 184,185
[rolling-upgrade-centos7-test](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/282/) build 282, 281
[rolling-upgrade-alternator-test](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-alternator-test/140/) build 140, 139

failed with error:
```
2023-03-20 14:46:29.043: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=8e11a28a-f438-4438-9666-d88650d81516, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 630, in test_rolling_upgrade
self.rollback_node(self.db_cluster.nodes[indexes[1]])
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 52, in inner
func_result = func(self, *args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/sct_events/group_common_events.py", line 250, in inner_func
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 300, in rollback_node
node.remoter.run(r'sudo yum downgrade scylla\* -y')
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo yum downgrade scylla\\* -y'
Exit code: 1
Stdout:
(8/10): scylla-server-5.2.0~rc2-0.20230228.908a  30 MB/s |  47 MB     00:01
(9/10): scylla-tools-core-5.2.0~rc2-0.20230228.  19 MB/s |  42 MB     00:02
(10/10): scylla-debuginfo-5.2.0~rc2-0.20230228.  28 MB/s | 252 MB     00:08
--------------------------------------------------------------------------------
Total                                            42 MB/s | 375 MB     00:08
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Stderr:
file /opt/scylladb/share/cassandra/pylib/cqlshlib/test/test_cqlsh_completion.py from install of scylla-tools-5.2.0~rc2-0.20230228.908a82bea064.noarch conflicts with file from package scylla-cqlsh-5.3.0~dev-0.20230316.5705df77a155.noarch
file /opt/scylladb/share/cassandra/pylib/cqlshlib/test/test_cqlsh_output.py from install of scylla-tools-5.2.0~rc2-0.20230228.908a82bea064.noarch conflicts with file from package scylla-cqlsh-5.3.0~dev-0.20230316.5705df77a155.noarch
file /opt/scylladb/share/cassandra/pylib/cqlshlib/test/test_keyspace_init.cql from install of scylla-tools-5.2.0~rc2-0.20230228.908a82bea064.noarch conflicts with file from package scylla-cqlsh-5.3.0~dev-0.20230316.5705df77a155.noarch
file /opt/scylladb/share/cassandra/pylib/cqlshlib/test/winpty.py from install of scylla-tools-5.2.0~rc2-0.20230228.908a82bea064.noarch conflicts with file from package scylla-cqlsh-5.3.0~dev-0.20230316.5705df77a155.noarch
file /opt/scylladb/share/cassandra/pylib/cqlshlib/tracing.py from install of scylla-tools-5.2.0~rc2-0.20230228.908a82bea064.noarch conflicts with file from package scylla-cqlsh-5.3.0~dev-0.20230316.5705df77a155.noarch
file /opt/scylladb/share/cassandra/pylib/cqlshlib/util.py from install of scylla-tools-5.2.0~rc2-0.20230228.908a82bea064.noarch conflicts with file from package scylla-cqlsh-5.3.0~dev-0.20230316.5705df77a155.noarch
file /opt/scylladb/share/cassandra/pylib/cqlshlib/wcwidth.py from install of scylla-tools-5.2.0~rc2-0.20230228.908a82bea064.noarch conflicts with file from package scylla-cqlsh-5.3.0~dev-0.20230316.5705df77a155.noarch
file /usr/bin/cqlsh from install of scylla-tools-5.2.0~rc2-0.20230228.908a82bea064.noarch conflicts with file from package scylla-cqlsh-5.3.0~dev-0.20230316.5705df77a155.noarch
file /usr/bin/cqlsh.py from install of scylla-tools-5.2.0~rc2-0.20230228.908a82bea064.noarch conflicts with file from package scylla-cqlsh-5.3.0~dev-0.20230316.5705df77a155.noarch
```

## Installation details
```
Base scylla version: 5.2.0~rc2-20230228.908a82bea064
Build id: c5e4affd90a7c49c0dcf1a00c3b8bc72a367aba2
Upgraded scylla version: 5.3.0~dev-20230316.5705df77a155
Build id: 3aa7c396c9e0eab7f08c8ab7dd82a548cf8d41e6
```

**Comment by soyacz** [comment]
@fruch shouldn't be docs updated too?

**Comment by fruch** [comment]
> @fruch shouldn't be docs updated too?

Docs for upgrade to 5.3 doesn't yet exist , but issues were opened as reminders
