### ISSUE TITLE
Python packages installation fail on timeout

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla-cqlsh#72]
https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2846/ failed on installing python packages

```
09:50:36  FAILED: tools/cqlsh/build/scylla-enterprise-cqlsh-2024.2.0~dev-0.20240312.e081b4e395db.noarch.tar.gz 
09:50:36  cd tools/cqlsh && ./reloc/build_reloc.sh --version $(<../../build/SCYLLA-PRODUCT-FILE)-$(sed 's/-/~/' <../../build/SCYLLA-VERSION-FILE)-$(<../../build/SCYLLA-RELEASE-FILE) --nodeps 
09:50:36  WARNING: The directory '/jenkins/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
09:50:36  * Creating venv isolated environment...
09:50:36  * Installing packages in isolated environment... (Cython, setuptools>=42, setuptools_scm[toml]>=6.2, wheel)
09:50:36  WARNING: The directory '/jenkins/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
09:50:36  Collecting wheel
09:50:36    Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
09:50:36       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 414.2 kB/s eta 0:00:00
09:50:36  Collecting Cython
09:50:36    Downloading Cython-3.0.9-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
09:50:36       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸      3.1/3.6 MB 13.4 kB/s eta 0:00:35
09:50:36  ERROR: Exception:
09:50:36  Traceback (most recent call last):
09:50:36    File "/tmp/build-env-4qblb1xy/lib64/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher
09:50:36      yield
09:50:36    File "/tmp/build-env-4qblb1xy/lib64/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
09:50:36      data = self._fp_read(amt) if not fp_closed else b""
09:50:36             ^^^^^^^^^^^^^^^^^^
09:50:36    File "/tmp/build-env-4qblb1xy/lib64/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 526, in _fp_read
09:50:36      return self._fp.read(amt) if amt is not None else self._fp.read()
09:50:36             ^^^^^^^^^^^^^^^^^^
09:50:36    File "/usr/lib64/python3.11/http/client.py", line 473, in read
09:50:36      s = self.fp.read(amt)
09:50:36          ^^^^^^^^^^^^^^^^^
09:50:36    File "/usr/lib64/python3.11/socket.py", line 706, in readinto
09:50:36      return self._sock.recv_into(b)
09:50:36             ^^^^^^^^^^^^^^^^^^^^^^^
09:50:36    File "/usr/lib64/python3.11/ssl.py", line 1314, in recv_into
09:50:36      return self.read(nbytes, buffer)
09:50:36             ^^^^^^^^^^^^^^^^^^^^^^^^^
09:50:36    File "/usr/lib64/python3.11/ssl.py", line 1166, in read
09:50:36      return self._sslobj.read(len, buffer)
09:50:36             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:50:36  TimeoutError: The read operation timed out
.
.
.
09:50:36  subprocess.CalledProcessError: Command '['/tmp/build-env-4qblb1xy/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-0_sgy70r.txt']' returned non-zero exit status 2.
09:50:36  
09:50:36  ERROR Command '['/tmp/build-env-4qblb1xy/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-0_sgy70r.txt']' returned non-zero exit status 2.
```

@fruch

**Comment by mykaul** [comment]
Too bad we don't cache wheels, which I assume rarely change.

**Comment by fruch** [comment]
> Too bad we don't cache wheels, which I assume rarely change.

no that rarely.
we do use ccache, but we don't mount in into dbuild the pip cache.

from cqlsh perspective, we can introduce a retry, that might help, a bit.
